---
title: "Materials"
---

<br>

## Day 1 Materials

* 08:00 - 09:00 Registration/breakfast
  + Breakfast offerings include bagels and coffee.
  
* 09:00 - 10:30 Wizarding Careers
    + Speaker: Dr. Higgledypuff, Hogwarts
    + Summary: In this session, we will present an overview of career tracks which are expected to become the most lucrative and demanded in the next decade. Advice regarding resume preparation and interviewing will be provided. 
    + Slides: 
    + Download Exercise files
* 10:30 - 11:00 Break
* 11:00 - 12:30 Recent Advances in Broom Travel
    + Speaker: Dr. Higgledypuff
    + Summary: In this session, we will present an overview of career tracks which are expected to become the most lucrative and demanded in the next decade. Advice regarding resume preparation and interviewing will be provided. 
    + Slides: 
    + Download Exercise files
* 12:30 - 14:00 Lunch
* 14:00 - 15:30 Intro to Quidditch
    + Speaker: Dr. Higgledypuff
    + Summary: In this session, we will present an overview of career tracks which are expected to become the most lucrative and demanded in the next decade. Advice regarding resume preparation and interviewing will be provided. 
    + Slides: 
    + Download Exercise files
* 15:30 - 16:00 Break
* 16:00 - 17:30 Potions I 
    + Speaker: Dr. Higgledypuff
    + Summary: In this session, we will present an overview of career tracks which are expected to become the most lucrative and demanded in the next decade. Advice regarding resume preparation and interviewing will be provided. 
    + Slides: 
    + Download Exercise files


<br>

## Day 2 Materials

* 08:00 - 09:00 Registration/breakfast
  + Breakfast offerings include bagels and coffee.
  
* 09:00 - 10:30 Wizarding Careers
    + Speaker: Dr. Higgledypuff, Hogwarts
    + Summary: In this session, we will present an overview of career tracks which are expected to become the most lucrative and demanded in the next decade. Advice regarding resume preparation and interviewing will be provided. 
    + Slides: 
    + Download Exercise files
* 10:30 - 11:00 Break
* 11:00 - 12:30 Recent Advances in Broom Travel
    + Speaker: Dr. Higgledypuff
    + Summary: In this session, we will present an overview of career tracks which are expected to become the most lucrative and demanded in the next decade. Advice regarding resume preparation and interviewing will be provided. 
    + Slides: 
    + Download Exercise files
* 12:30 - 14:00 Lunch
* 14:00 - 15:30 Intro to Quidditch
    + Speaker: Dr. Higgledypuff
    + Summary: In this session, we will present an overview of career tracks which are expected to become the most lucrative and demanded in the next decade. Advice regarding resume preparation and interviewing will be provided. 
    + Slides: 
    + Download Exercise files
* 15:30 - 16:00 Break
* 16:00 - 17:30 Potions I 
    + Speaker: Dr. Higgledypuff
    + Summary: In this session, we will present an overview of career tracks which are expected to become the most lucrative and demanded in the next decade. Advice regarding resume preparation and interviewing will be provided. 
    + Slides: 
    + Download Exercise files
